name: Build GH-Injector-GUI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake qtbase5-dev

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GH-Injector-GUI
          path: build/GH-Injector-GUI
